//! Shared segmentation geometry for the HKM rungs — ONE definition of the
//! cell walls, and one comparison against them.
//!
//! The cells are [2^(kΔ), 2^((k+1)Δ)), so the walls are irrational and any
//! implementation has to choose integer representatives. The trap — the same
//! one that produced pistar's half-ulp band bug — is using TWO float paths
//! for the same wall:
//!
//!     kbar(n)  = floor(log2(n) / Δ)                    via @log2
//!     1bar[k]  = ceil(2^((k+1)Δ)) - ceil(2^(kΔ))       via exp2
//!
//! Those disagree whenever a wall lands within a rounding error of an
//! integer: n is then in cell k by one path and cell k−1 by the other. It is
//! invisible until it isn't — 1e6 through 1e9 are clean, 1e10 is wrong by
//! exactly 7 units, 1e11 is clean again.
//!
//! Fix: materialise the walls ONCE as an integer table, and make every
//! question ask that table. Nothing else may compute a wall.
//!
//! What the table must satisfy, and why:
//!
//!   wall[k] = ceil(2^(kΔ)) exactly.  R1's one-sidedness proof needs
//!   wall[i]·wall[j] >= wall[i+j] (super-multiplicativity): if kbar(m) = a and
//!   kbar(p_i) = b_i then m·d >= wall[a]·prod wall[b_i] >= wall[a+sum b], and
//!   m·d <= N < wall[K+1] then forces a + sum b <= K. Ceiling gives it for
//!   free — wall[i]·wall[j] is an integer >= 2^(iΔ)·2^(jΔ) = 2^((i+j)Δ),
//!   hence >= ceil of it — but ONLY if the ceiling is the true one.
//!
//! A single f64 exp2 cannot decide that ceiling: its ~1 ulp of relative error
//! is ~1e-4 in absolute terms at a wall of 1e12, so any wall whose fractional
//! part is near 0 or 1 is a coin flip, and a wall that rounds DOWN across an
//! integer breaks super-multiplicativity silently. An arbitrary upward nudge
//! "fixes" that by corrupting ~10% of the walls instead.
//!
//! So the walls are generated by double-double recurrence: r = 2^Δ to ~2^-106
//! via the exp series (Δ·ln2 is small, so it converges immediately), then
//! w_k = w_{k-1}·r in dd. After K = 1e6 steps the accumulated relative error
//! is ~1e-26 — about 1e-14 absolute at a wall of 1e12 — so the ceiling is
//! decided by a margin of eleven orders of magnitude rather than being a coin
//! flip. The ceiling itself is then taken exactly off the (hi, lo) pair.

const std = @import("std");

pub const Geom = struct {
    delta: f64,
    K: usize, // = kbar(N)
    wall: []u64, // wall[k] = ceil(2^(kΔ)), non-decreasing, wall[0] = 1

    pub fn deinit(g: *Geom, gpa: std.mem.Allocator) void {
        gpa.free(g.wall);
    }

    /// The cell of n, by integer comparison against the table. @log2 supplies
    /// a starting guess only — the answer comes from the walls, so the guess
    /// being a hair wrong costs a loop iteration, not correctness.
    /// Saturates at K+1: every k > K is equally rejected by the k1+k2 <= K
    /// admission test, so there is no need to size the table past it.
    pub fn kbar(g: *const Geom, n: u64) usize {
        const top = g.wall.len - 2;
        var k: usize = @intFromFloat(@floor(@log2(@as(f64, @floatFromInt(n))) / g.delta));
        if (k > top) k = top;
        while (k + 1 < g.wall.len and n >= g.wall[k + 1]) {
            if (k == top) return top;
            k += 1;
        }
        while (k > 0 and n < g.wall[k]) k -= 1;
        return k;
    }

    /// #{ m >= 1 : kbar(m) = k } — the segmentation of the constant 1.
    pub fn cell(g: *const Geom, k: usize) u64 {
        return g.wall[k + 1] - g.wall[k];
    }

    /// #{ m >= 1 : kbar(m) <= j }. Exactly wall[j+1] - 1, since the m counted
    /// are precisely 1..wall[j+1]-1 — no prefix sum needed.
    pub fn upto(g: *const Geom, j: usize) u64 {
        return g.wall[j + 1] - 1;
    }
};

// ---- minimal double-double: enough for the wall recurrence, nothing more.

const LN2_HI: f64 = 0.6931471805599453;
const LN2_LO: f64 = 2.3190468138462996e-17;

fn twoSum(a: f64, b: f64) [2]f64 {
    const s = a + b;
    const bb = s - a;
    return .{ s, (a - (s - bb)) + (b - bb) };
}

fn twoProd(a: f64, b: f64) [2]f64 {
    const p = a * b;
    return .{ p, @mulAdd(f64, a, b, -p) };
}

fn ddMul(a: [2]f64, b: [2]f64) [2]f64 {
    const p = twoProd(a[0], b[0]);
    const e = p[1] + (a[0] * b[1] + a[1] * b[0]);
    return twoSum(p[0], e);
}

fn ddAddD(a: [2]f64, b: f64) [2]f64 {
    const s = twoSum(a[0], b);
    return twoSum(s[0], s[1] + a[1]);
}

/// 2^delta in double-double, via exp(delta*ln2) summed in reverse. delta <= 1
/// so x <= 0.694 and 30 terms are far past 2^-106.
fn twoPowDD(delta: f64) [2]f64 {
    const x = ddMul(.{ LN2_HI, LN2_LO }, .{ delta, 0 });
    var acc: [2]f64 = .{ 0, 0 };
    var n: f64 = 30;
    while (n >= 1) : (n -= 1) {
        acc = ddMul(ddAddD(acc, 1.0), .{ x[0] / n, x[1] / n });
    }
    return ddAddD(acc, 1.0);
}

/// ceil of the exact value hi + lo. The gap ceil(hi) - hi is computed exactly
/// (both operands are within a factor of two), so the comparison is exact —
/// including the hi-is-an-integer case, where gap = 0 and any positive lo
/// correctly pushes the ceiling up one.
fn ddCeil(w: [2]f64) u64 {
    const c = @ceil(w[0]);
    const gap = c - w[0];
    return @intFromFloat(if (w[1] <= gap) c else c + 1);
}

/// Build the geometry for a given N and Δ. K is then read back off the table
/// rather than recomputed, so K = kbar(N) holds by construction.
pub fn build(gpa: std.mem.Allocator, N: u64, delta: f64) !Geom {
    std.debug.assert(delta > 0 and delta <= 1.0);
    const kest: usize = @intFromFloat(@floor(@log2(@as(f64, @floatFromInt(N))) / delta));
    const len = kest + 4;
    const wall = try gpa.alloc(u64, len);
    const r = twoPowDD(delta);
    var w: [2]f64 = .{ 1, 0 };
    var prev: u64 = 1;
    wall[0] = 1;
    var k: usize = 1;
    while (k < len) : (k += 1) {
        w = ddMul(w, r);
        var v = ddCeil(w);
        if (v < prev) v = prev; // non-decreasing; equal walls = empty cells
        wall[k] = v;
        prev = v;
    }
    var g = Geom{ .delta = delta, .K = 0, .wall = wall };
    g.K = g.kbar(N);
    // super-multiplicativity, spot-checked on the cheapest necessary case
    // (j = 1); a full O(K^2) sweep is not affordable at K ~ 1e6.
    var i: usize = 0;
    while (i + 1 < len) : (i += 1) {
        if (@as(u128, wall[i]) * @as(u128, wall[1]) < @as(u128, wall[i + 1])) return error.WallsNotSuperMultiplicative;
    }
    return g;
}
